version: '3.8'

networks:
  dev:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: home_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/code/staticfiles
    networks:
      - dev
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/staticfiles
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - dev


volumes:
  static_volume:
  db_data:



